# Generated by Django 4.2.5 on 2023-09-30 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesson_02_hw_app", "0003_remove_order_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(default=datetime.date(2023, 9, 30)),
        ),
    ]
