# Generated by Django 4.2.5 on 2023-10-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesson_02_hw_app", "0006_product_image_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_name",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="media/empty.jpg", upload_to="media/"),
        ),
    ]
